### PR TITLE
Add CocoPod support

### PR DESCRIPTION
**Pull request by pushpak**
You guys need to push to cocoapod.

### CODE REVIEW

**Comment by simonrice** [comment]
+1 : you beat me to it there

**Comment by bartg** [comment]
Please merge this, would be much easier to do update process, and much easier to add this to new projects. 

+1 !

**Comment by mattiasjahnke** [comment]
@pushpak could you please update the iOS platform to 7.1 in the readme and podspec?

We'll probably reformat parts of the readme to better visualize the steps when it's merged.

**Comment by pushpak** [comment]
@mattiasjahnke Done! Please feel free to merge and do whatever changes necessary.

**Pull request merged**
